### ISSUE TITLE
HU1: Consultar mangas disponibles

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/manga-api#9]
HU1: Como usuario debo poder consultar una lista de mangas disponibles. La lista deberá contener información adicional como nombre del manga, fecha de actualización, etc.﻿

**Comment by antoniogamiz** [comment]
I still need to do the UI, so I will reopen.

**Comment by JJ** [comment]
Me tienes hecho un lío con los idiomas. Ya solo te falta ponerlo en klingon o en euskera.

**Comment by antoniogamiz** [comment]
I know, lo próximo es esperanto, que es el lenguaje universal.

**Comment by JJ** [comment]
Esta HU no dice qué ocurre si no hay ningún manga disponible. "etc" no es preciso, hay que precisar exactamente qué tiene que devolver. No dice los criterios de consulta.

**Comment by JJ** [comment]
Agh, está acoplado la petición al API de manganelo de las peticiones al propio API. Eso NO se hace. O manejas las promesas y peticiones asíncronas de forma razonable, o usar algún sistema de colas para poder ir sirviendo esas peticiones.

**Comment by JJ** [comment]
No puedes poner URLs ni en general ninguna constante en el código. Toda petición de datos externos se debe "inyectar" usando desacoplamiento de dependencias.

**Comment by JJ** [comment]
No veo que se añada ningún valor al API original. ¿Por qué querría alguien hacer peticiones a tu API si lo que hace es hacer peticiones al otro API y servirlas tal cual? ¿Qué valor tiene eso?
